export enum UserType {
  ADMIN = "ADMIN",
  MANAGER = "MANAGER",
  CLIENT = "CLIENT",
  EMPLOYEE = "EMPLOYEE",
}

export enum PermissionType {
  MANAGE_ALL = "MANAGE_ALL",
  MANAGE_CLIENT = "MANAGE_CLIENT",
  MANAGE_EMPLOYEE = "MANAGE_EMPLOYEE",
  MANAGE_CONSULTANT = "MANAGE_CONSULTANT",
  MANAGE_INTERN = "MANAGE_INTERN",
  MANAGE_REPORT = "MANAGE_REPORT",
  CREATE_REPORT = "CREATE_REPORT",
}

export enum EmployeeType {
  CONSULTANT = 1,
  INTERN = 2,
}
